on: push
name: Unit Test
jobs:
  unitTest:
    name: Unit Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
